#!/bin/bash
export GITLAB_HOST="https://gitlab.services-for-app.space:443/"
export GITLAB_USER="User"
export GITLAB_PASSWORD="Password"
response=$(curl --request POST "${GITLAB_HOST}/oauth/token" \
--header "Content-Type: application/json" \
--data '{"grant_type": "password", "username": "'"${GITLAB_USER}"'", "password": "'"${GITLAB_PASSWORD}"'"}')

access_token=$(echo "${response}" | jq -r '.access_token')
echo "${access_token}"

response2=$(curl --request GET "$GITLAB_HOST/api/v4/users?username=$GITLAB_USER" \
--header "Content-Type: application/json" \
--data '{"grant_type": "password", "username": "'"${GITLAB_USER}"'", "password": "'"${GITLAB_PASSWORD}"'"}')
id_user=$(echo "${response2}" | jq -r '.[0].id')
echo "${id_user}"

create_token_response=$(curl --request POST "${GITLAB_HOST}/api/v4/users/${id_user}/impersonation_tokens" \
--header "Authorization: Bearer ${access_token}" \
--header "Content-Type: application/json" \
--data '{"name": "MyToken", "expires_at": "2024-01-01", "scopes": ["api", "read_user"]}')

echo "${create_token_response}"
